### ISSUE TITLE
Notice: Undefined variable: argc in C:\wamp\www\Vipet\conv_fnames.php on line 271

### ISSUE THREAD

**Issue by zomorango** [barakravid/codecharge_php7fix#1]
Hi,

I've made  a copy ofr the conv_fnames.php to my  codecharge studio published project folder and run the conv_fnames.php and get this error.

**Comment by barakravid** [comment]
did you run from command line?

**Comment by zomorango** [comment]
Hi, 
ho sorry, my mistake, 
It runs ok now.

Thanks
